services:
  mysql-dev:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: northwind
    networks:
      - mysql
    ports:
      - "3306:3306"
    volumes:
      - ./sampledbs:/docker-entrypoint-initdb.d 